[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  branch = "master"
  name = "github.com/jpillora/go-tld"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.1.1"

[prune]
  go-tests = true
  unused-packages = true
